# Uncomment the next line to define a global platform for your project

target 'Sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  platform :ios, '13.2'

  # Pods for Sample
  pod 'Armin', :path => '../Armin.podspec'
end

target 'Sample-Mac' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  platform :osx, '10.15'

  # Pods for Sample
  pod 'Armin', :path => '../Armin.podspec'
end


target 'Sample-OC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  platform :ios, '13.2'

  # Pods for Sample
  pod 'Armin', :path => '../Armin.podspec'
end